<?php

// Straight English equivalent of lang/ar/notifications.php. Both files must
// stay key-for-key identical (pinned by test); only the wording differs.
return [
    'credentials' => "Hi :name 👋\n\n❌ We could not sign in to the EA account — order #:order_number\n\nThe sign-in details (email or password) are not right.\n\nWhat to do:\n1️⃣ Check the email and password (try signing in yourself once to be sure).\n2️⃣ Open your order link and update them from “Update order details” — it continues on its own:\n:link",
    'backup_codes' => "Hi :name 👋\n\n❌ The backup codes are not right — order #:order_number\n\nWhat to do:\n1️⃣ Generate new codes and make sure they are unused.\n2️⃣ Open your order link and update the codes from “Update order details” — it continues on its own:\n:link\n\n🎥 How to generate them:\nhttps://arab-ut.com/ea-backup-codes-guide/page-699997932",
    'platform' => "Hi :name 👋\n\n🛑 The selected platform does not match — order #:order_number\n\nIt looks like you picked a platform different from your account's real one, and each platform is priced differently.\n\nWhat to do:\n1️⃣ Check your account's platform.\n2️⃣ Open your order link and fix the details from “Update order details”:\n:link",
    'market_locked' => "Hi :name 👋\n\n⛔ The transfer market is not available on your account — order #:order_number\n\nYour account still has no market access in the web or companion app (EA usually opens it after enough play inside the game).\n\nWhat to do:\n1️⃣ Play 3 matches a day until the market opens.\n2️⃣ Then open your order link and press “Start the order” — it continues on its own:\n:link",
    'insufficient_coins' => "Hi :name 👋\n\n⚠️ Your coin balance is too low — order #:order_number\n\nA safe transfer needs at least 1,500 coins in your account.\n\nWhat to do:\n1️⃣ Top it up (play a match or sell a player from your club).\n2️⃣ Then open your order link and press “Start the order” — it continues on its own:\n:link",
    'active_session' => "Hi :name 👋\n\n⚠️ The account is still signed in — order #:order_number\n\nWe cannot start working while you are connected to the account.\n\nThe quick fix:\n1️⃣ Open the game on your device.\n2️⃣ Enter Ultimate Team.\n3️⃣ Go back to the main menu properly.\n4️⃣ Make sure the companion app is fully closed.\n\nThen open your order link, press “Start the order”, and good luck:\n:link",
    'no_club' => "Hi :name 👋\n\n⚠️ There is no Ultimate Team club on the account — order #:order_number\n\nWhat to do:\n1️⃣ Open the game and create your club.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'transfer_list_full' => "Hi :name 👋\n\n📋 Your transfer list is full — order #:order_number\n\nThere is no room left for the delivery.\n\nWhat to do:\n1️⃣ Clear some space in the list.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'captcha' => "Hi :name 👋\n\n🧩 EA is asking for a verification code on the account — order #:order_number\n\nWhat to do:\n1️⃣ Open the Web App and solve it.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'unassigned' => "Hi :name 👋\n\n📦 There are unassigned items on the account blocking the delivery — order #:order_number\n\nWhat to do:\n1️⃣ Open them or move them to your club.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'account_banned' => "Hi :name 👋\n\n⚠️ We ran into a sign-in problem — order #:order_number\n\nEA may have restricted the account.\n\nWhat to do:\n1️⃣ Press “Start the order” from your order link to try again:\n:link\n2️⃣ And if your details look wrong, update them from “Update order details”.",
    'two_factor_off' => "Hi :name 👋\n\n🔐 Two-factor verification is off on the account — order #:order_number\n\nWe need it to keep going.\n\nWhat to do:\n1️⃣ Turn it on in your EA security settings.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'email_confirm' => "Hi :name 👋\n\n📧 EA wants the email address confirmed — order #:order_number\n\nWhat to do: confirm it from the EA message, then follow your order here:\n:link",
    'web_app_locked' => "Hi :name 👋\n\n🌐 The Web App was never opened on this account — order #:order_number\n\nWe need it to finish the work.\n\nWhat to do:\n1️⃣ Open it once in a browser.\n2️⃣ Then open your order link and press “Start the order”:\n:link",
    'market_locked_challenge' => "Hi :name 👋\n\n⛔ The transfer market is not available on your account — order #:order_number\n\nYour account still has no market access in the web or companion app (EA usually opens it after enough play inside the game).\n\nWhat to do:\n1️⃣ Play 3 matches a day until the market opens.\n2️⃣ Then open your order link and press “Try again” — it continues on its own:\n:link",
    'insufficient_coins_challenge' => "Hi :name 👋\n\n⚠️ Your coin balance is too low — order #:order_number\n\nA safe transfer needs at least 1,500 coins in your account.\n\nWhat to do:\n1️⃣ Top it up (play a match or sell a player from your club).\n2️⃣ Then open your order link and press “Try again” — it continues on its own:\n:link",
    'active_session_challenge' => "Hi :name 👋\n\n⚠️ The account is still signed in — order #:order_number\n\nWe cannot start working while you are connected to the account.\n\nThe quick fix:\n1️⃣ Open the game on your device.\n2️⃣ Enter Ultimate Team.\n3️⃣ Go back to the main menu properly.\n4️⃣ Make sure the companion app is fully closed.\n\nThen open your order link, press “Try again”, and good luck:\n:link",
    'no_club_challenge' => "Hi :name 👋\n\n⚠️ There is no Ultimate Team club on the account — order #:order_number\n\nWhat to do:\n1️⃣ Open the game and create your club.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'transfer_list_full_challenge' => "Hi :name 👋\n\n📋 Your transfer list is full — order #:order_number\n\nThere is no room left for the delivery.\n\nWhat to do:\n1️⃣ Clear some space in the list.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'captcha_challenge' => "Hi :name 👋\n\n🧩 EA is asking for a verification code on the account — order #:order_number\n\nWhat to do:\n1️⃣ Open the Web App and solve it.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'unassigned_challenge' => "Hi :name 👋\n\n📦 There are unassigned items on the account blocking the delivery — order #:order_number\n\nWhat to do:\n1️⃣ Open them or move them to your club.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'account_banned_challenge' => "Hi :name 👋\n\n⚠️ We ran into a sign-in problem — order #:order_number\n\nEA may have restricted the account.\n\nWhat to do:\n1️⃣ Press “Try again” from your order link to try again:\n:link\n2️⃣ And if your details look wrong, update them from “Update order details”.",
    'two_factor_off_challenge' => "Hi :name 👋\n\n🔐 Two-factor verification is off on the account — order #:order_number\n\nWe need it to keep going.\n\nWhat to do:\n1️⃣ Turn it on in your EA security settings.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'web_app_locked_challenge' => "Hi :name 👋\n\n🌐 The Web App was never opened on this account — order #:order_number\n\nWe need it to finish the work.\n\nWhat to do:\n1️⃣ Open it once in a browser.\n2️⃣ Then open your order link and press “Try again”:\n:link",
    'order_cancelled' => "Hi :name 👋\n\n🛑 An update on your order #:order_number\n\nThe order was cancelled. You can see the details on your order page:\n:link",
    'order_refunded' => "Hi :name 👋\n\n💸 An update on your order #:order_number\n\nThe order amount was refunded. You can see the details on your order page:\n:link",
];
