import type {
    AdminServicePricingData,
    AdminServicePricingUrls,
    AdminTeamData,
    AdminTeamUrls,
    AdminTranslations,
} from '@/types/admin';

export const englishAdminUi: AdminTranslations = {
    brand: 'Arab UT',
    common: {
        cancel: 'Cancel',
        dismiss: 'Dismiss',
        logout: 'Log out',
        noData: 'No data',
        retry: 'Try again',
    },
    navigation: {
        close: 'Close Admin navigation',
        customers: 'Customers',
        open: 'Open Admin navigation',
        orders: 'Orders',
        overview: 'Overview',
        products: 'Products',
        quick: 'quick navigation',
        settings: 'Settings',
    },
    overview: {
        capturedRevenue: 'Captured revenue',
        description:
            'A focused summary of orders and payments that need attention.',
        failedPayments: 'Failed payments',
        failedRefunds: 'Failed refunds',
        headTitle: 'Operational overview',
        inProgressOrders: 'Orders in progress',
        noAudit: 'There is no recent Admin activity.',
        noUnresolved: 'There are no unresolved orders.',
        oldestUnresolved: 'Oldest unresolved order',
        pendingPayments: 'Pending payments',
        range7: 'Last 7 days',
        range30: 'Last 30 days',
        receivedOrders: 'Received orders',
        recentAudit: 'Recent Admin activity',
        title: 'Operations dashboard',
        waitingForCustomer: 'Waiting for customer',
        totalOrders: 'Total placed orders',
        newCustomers: 'New customers',
        needsAttention: 'Needs attention',
        previousPeriod: 'vs. previous period',
        newThisPeriod: 'New this period',
        noChange: 'No change',
        revenueTrendTitle: 'Captured revenue trend',
        revenueTrendDescription:
            'Daily gross captured revenue over the selected window',
        orderDistributionTitle: 'Order status distribution',
        orderDistributionDescription:
            'All orders placed in the selected window by status',
        revenueTableAria: 'Daily captured revenue summary',
        date: 'Date',
        revenue: 'Revenue',
        status: 'Status',
        count: 'Count',
        noRevenue: 'No captured revenue in this period.',
        noOrdersInPeriod: 'No orders placed in this period.',
        recentOrdersTitle: 'Recent placed orders',
        recentOrdersDescription:
            'Latest orders placed during the selected window',
        orderNumber: 'Order',
        orderTotal: 'Total',
        orderPlacedAt: 'Placed at',
        noRecentOrders: 'There are no recent orders in this period.',
        attentionRailTitle: 'Operational focus',
    },
    orders: {
        allPaymentStatuses: 'All payment statuses',
        allPlatforms: 'All platforms',
        allServices: 'All services',
        allStatuses: 'All statuses',
        apply: 'Apply',
        clearAll: 'Clear all',
        clearSearch: 'Clear search',
        columns: 'Columns',
        customer: 'Customer',
        dateFrom: 'Date from',
        dateTo: 'Date to',
        description:
            'View and filter all customer orders across services and platforms.',
        filterPayment: 'Filter by payment status',
        filterPlatform: 'Filter by platform',
        filterService: 'Filter by service',
        filterStatus: 'Filter by status',
        filters: 'Filters',
        headTitle: 'Orders',
        items: 'Items',
        loading: 'Loading orders…',
        errorTitle: 'Orders unavailable',
        loadFailed:
            'We could not update the orders list. Check your connection and try again.',
        tableLabel: 'Orders list',
        firstPage: 'First page',
        lastPage: 'Last page',
        next: 'Next',
        noOrders: 'No orders found.',
        noOrdersMatching: 'No orders match your filter criteria.',
        noPayment: 'No payment',
        of: 'of',
        order: 'Order',
        page: 'Page',
        payment: 'Payment',
        perPage: 'Per page',
        placedAt: 'Placed at',
        platform: 'Platform',
        platforms: {
            pc: 'PC',
            playstation: 'PlayStation',
            xbox: 'Xbox',
        },
        previous: 'Previous',
        resetFilters: 'Reset filters',
        results: 'results',
        searchButton: 'Search',
        searchLabel: 'Search orders',
        searchPlaceholder: 'Search by order #, public ID, email, or phone…',
        service: 'Service',
        selectAll: 'Select all rows on this page',
        selectRow: 'Select row',
        selectedRows: ':count of :total row(s) selected',
        services: {
            coins: 'Coins',
            fut_champions: 'FUT Champions',
            objectives: 'Objectives',
            rivals: 'Division Rivals',
            sbc: 'SBC',
        },
        showing: 'Showing',
        sortBy: 'Sort by :column',
        sortAscending: 'sorted ascending',
        sortDescending: 'sorted descending',
        status: 'Status',
        title: 'Orders',
        to: 'to',
        toggleColumns: 'Toggle columns',
        total: 'Total',
    },
    orderDetail: {
        headTitle: 'Order :number',
        title: 'Order :number',
        backToOrders: 'Back to orders',
        customerSection: 'Customer information',
        paymentSection: 'Payment & breakdown',
        itemsSection: 'Order items',
        historySection: 'Status history',
        auditSection: 'Admin audit activity',
        transitionsTitle: 'Change order status',
        transitionsDescription:
            'Transition this order to a valid next lifecycle state.',
        noHistory: 'No status history recorded.',
        noAudit: 'No audit logs recorded for this order.',
        noItems: 'No items in this order.',
        noDiscounts: 'No discounts applied.',
        noPayments: 'No payments recorded.',
        noRefunds: 'No refunds recorded.',
        customerName: 'Customer name',
        customerEmail: 'Email',
        customerPhone: 'Phone',
        subtotal: 'Subtotal',
        discount: 'Discount',
        wallet: 'Wallet balance applied',
        payment: 'Payment collected',
        total: 'Total',
        currency: 'Currency',
        placedAt: 'Placed at',
        paidAt: 'Paid at',
        completedAt: 'Completed at',
        cancelledAt: 'Cancelled at',
        item: 'Item',
        service: 'Service',
        platform: 'Platform',
        quantity: 'Quantity',
        unitPrice: 'Unit price',
        status: 'Status',
        source: 'Source',
        actor: 'Staff member',
        date: 'Date',
        changeStatusTo: 'Change status to :status',
        confirmModalTitle: 'Confirm status change',
        confirmModalDescription:
            'Are you sure you want to change order :number to :status? This will update active order items and record a staff audit log.',
        confirmCancelDescription:
            'Are you sure you want to cancel order :number? This action is permanent and will cancel all active items in this order.',
        confirmCompleteDescription:
            'Are you sure you want to complete order :number? This will mark matching active items as completed.',
        confirmButton: 'Confirm transition',
        cancelButton: 'Cancel',
        updating: 'Updating status…',
        statusUpdated: 'Order status updated successfully.',
        conflictError:
            'This order was modified by another action. Current status is :status. Please review before proceeding.',
        transitionFailed:
            'We could not update the order status. Please check your connection and try again.',
        forbiddenTransition:
            'You do not have permission to perform this status transition.',
        noTransitionsAvailable:
            'No further status transitions are available for this order.',
        secrets: {
            title: 'Credentials',
            loading: 'Loading credentials…',
            retryButton: 'Retry',
            copyButton: 'Copy',
            copied: 'Copied to clipboard',
            purgedNotice:
                'Credentials for this item have been purged and are no longer available.',
            revealedCredentialsTitle: 'Decrypted credentials',
            genericError: 'Unable to reveal credentials. Please try again.',
            networkError:
                'Network error. Please check your connection and try again.',
            forbiddenError: 'You do not have permission to view credentials.',
        },
        refundsTitle: 'Refunds',
        refund: {
            title: 'Issue Paylink refund',
            description:
                'Refund the captured payment back to the customer via Paylink.',
            amountLabel: 'Refund amount',
            reasonLabel: 'Staff reason',
            reasonPlaceholder:
                'Enter internal reason for the refund (up to 500 characters)…',
            reasonRequired: 'A refund reason is required.',
            reasonMaxLength: 'Refund reason cannot exceed 500 characters.',
            submitButton: 'Refund order',
            processingButton: 'Processing refund…',
            confirmModalTitle: 'Confirm Paylink refund',
            confirmModalDescription:
                'Are you sure you want to refund :amount for order :number? This will return the payment to the customer and mark the order as refunded.',
            confirmButton: 'Issue full refund',
            cancelButton: 'Cancel',
            successTitle: 'Refund completed',
            successMessage: 'Refund processed successfully.',
            errorTitle: 'Refund error',
            fullRefundRequired:
                'Paylink supports a full original-payment refund only.',
            unavailable: 'This order cannot be refunded automatically.',
            providerUnavailable:
                'The refund provider is currently unavailable. Please try again later.',
            rateLimited:
                'Too many refund requests. Please wait :seconds seconds before trying again.',
            rateLimitedGeneric:
                'Too many refund requests. Please wait before trying again.',
            genericError:
                'Unable to process refund. Please check your connection and try again.',
            networkError:
                'Network error. Please check your connection and try again.',
            passwordModalTitle: 'Confirm your password',
            passwordModalDescription:
                'For security, please enter your password to confirm this refund.',
            passwordLabel: 'Password',
            passwordPlaceholder: 'Enter your current password',
            confirmPasswordButton: 'Confirm password',
            confirmingPassword: 'Verifying password…',
            invalidPassword: 'The provided password was incorrect.',
        },
    },
    statuses: {
        authorized: 'Authorized',
        cancelled: 'Cancelled',
        completed: 'Completed',
        failed: 'Failed',
        in_progress: 'In progress',
        paid: 'Paid',
        partially_refunded: 'Partially refunded',
        pending: 'Pending',
        pending_payment: 'Pending payment',
        received: 'Received',
        refunded: 'Refunded',
        waiting_for_customer: 'Waiting for customer',
    },
    mfa: {
        accessDenied:
            'Your account is no longer eligible to manage Admin security.',
        configured: 'Two-factor authentication is on',
        configuredDescription: 'Your account is protected and can enter Admin.',
        confirm: 'Confirm two-factor setup',
        confirmCode: 'Authenticator code',
        confirmPasswordAgain: 'Confirm password',
        confirmRegenerate: 'Replace recovery codes',
        confirming: 'Confirming the code…',
        description:
            'Use an authenticator app to protect your account before entering Admin.',
        enable: 'Start two-factor setup',
        enabling: 'Creating your setup code…',
        eyebrow: 'Admin security',
        failed: 'We could not complete the security request. Your account settings were not changed.',
        headTitle: 'Protect your Admin account',
        hideRecoveryCodes: 'Hide recovery codes',
        invalidCode:
            'That code is invalid or expired. Check your authenticator app and try again.',
        openAccountSecurity: 'Open account security',
        passwordConfirmationExpired:
            'Your password confirmation expired. Confirm it again to continue.',
        qrAlt: 'QR code for adding Arab UT to an authenticator app',
        rateLimited:
            'Too many attempts were sent. Wait one minute before trying again.',
        recoveryTitle: 'Recovery codes',
        recoveryWarning:
            'Keep these codes somewhere safe. Each code can be used only once.',
        regenerateDescription:
            'Your current codes will stop working immediately. Be ready to save the new codes.',
        regenerateRecoveryCodes: 'Create new recovery codes',
        regenerateTitle: 'Replace recovery codes?',
        regenerating: 'Creating new codes…',
        retryAfterWait: 'Reload the page after one minute',
        returnToStore: 'Return to the store',
        scanDescription:
            'Open your authenticator app and scan the code. Then enter the 6-digit code it shows.',
        scanTitle: 'Scan the QR code',
        sessionExpired: 'Your session expired. Sign in again to continue.',
        setupPassword: 'Set a password first',
        setupPasswordDescription:
            'Add a password in account security, then return to finish two-factor setup.',
        showRecoveryCodes: 'Show recovery codes',
        signIn: 'Sign in again',
        startDescription:
            'We will create a QR code for this account. Scan it in your authenticator app, then confirm the code it shows.',
        startTitle: 'Connect your authenticator app',
        title: 'Set up two-factor authentication',
        trustedDevicesTitle: 'Trusted browsers',
        trustedDevicesDescription:
            ':count browser(s) currently trusted. Trusted browsers skip the two-factor challenge for up to :days days.',
        trustedDevicesNone:
            'No browsers are currently trusted. Every sign-in will require a two-factor code.',
        forgetTrustedDevices: 'Forget trusted browsers',
        forgettingTrustedDevices: 'Forgetting browsers…',
        forgetTrustedDevicesTitle: 'Forget all trusted browsers?',
        forgetTrustedDevicesDescription:
            'Every browser, including this one, will have to enter a two-factor code again at the next sign-in.',
        confirmForgetTrustedDevices: 'Forget all browsers',
    },
    customers: {
        allStatuses: 'All statuses',
        clearSearch: 'Clear search',
        columns: 'Columns',
        createdAt: 'Registered at',
        customer: 'Customer',
        dateFrom: 'Date from',
        dateTo: 'Date to',
        description: 'View and filter all registered customer accounts.',
        email: 'Email',
        errorTitle: 'Customers unavailable',
        filterStatus: 'Filter by status',
        firstPage: 'First page',
        headTitle: 'Customers',
        lastOrderAt: 'Last order',
        lastPage: 'Last page',
        loadFailed:
            'We could not update the customers list. Check your connection and try again.',
        loading: 'Loading customers…',
        name: 'Name',
        next: 'Next',
        noCustomers: 'No customers found.',
        noCustomersMatching: 'No customers match your filter criteria.',
        noOrders: 'No orders',
        noPhone: 'No phone',
        of: 'of',
        orders: 'Orders',
        ordersCount: 'Orders',
        page: 'Page',
        perPage: 'Per page',
        phone: 'Phone',
        previous: 'Previous',
        resetFilters: 'Reset filters',
        results: 'results',
        searchButton: 'Search',
        searchLabel: 'Search customers',
        searchPlaceholder: 'Search by name, email, phone, or public ID…',
        selectAll: 'Select all rows on this page',
        selectRow: 'Select row',
        selectedRows: ':count of :total row(s) selected',
        showing: 'Showing',
        sortBy: 'Sort by :column',
        sortAscending: 'sorted ascending',
        sortDescending: 'sorted descending',
        status: 'Status',
        statusActive: 'Active',
        statusSuspended: 'Suspended',
        tableLabel: 'Customers list',
        title: 'Customers',
        to: 'to',
        toggleColumns: 'Toggle columns',
        actions: 'Actions',
        totalSpent: 'Total spent',
        viewDetail: 'View customer',
        walletBalance: 'Wallet balance',
    },
    customerDetail: {
        accountStatus: 'Account status',
        action: 'Action',
        actor: 'Staff member',
        auditSection: 'Staff audit activity',
        backToCustomers: 'Back to customers',
        cancelButton: 'Cancel',
        caseReferenceHelp:
            'Alphanumeric and . _ : - characters only, up to 64 characters.',
        caseReferenceLabel: 'Case reference (optional)',
        caseReferencePlaceholder: 'e.g. TICKET-1234 or CR-5678',
        confirmPasswordButton: 'Confirm password',
        confirmReactivate: 'Reactivate customer',
        confirmSuspend: 'Suspend customer',
        confirmingPassword: 'Verifying password…',
        conflictError:
            'This customer was modified by another action. Current status is :status. Please review before proceeding.',
        date: 'Date',
        email: 'Email',
        emailUnverified: 'Unverified',
        emailVerified: 'Verified',
        entryAmount: 'Amount',
        entryDate: 'Date',
        entryReference: 'Reference',
        entryType: 'Type',
        forbiddenError: 'You do not have permission to update customer status.',
        headTitle: 'Customer :name',
        identitySection: 'Customer information',
        editDetailsButton: 'Edit details',
        editContactTitle: 'Edit customer details',
        editContactDescription:
            "Update the customer's name, email address, and phone number.",
        firstNameLabel: 'First name',
        lastNameLabel: 'Last name',
        emailLabel: 'Email address',
        phoneLabel: 'Phone number',
        phoneHelp:
            'Use international E.164 format (e.g. +966501234567). Leave blank to remove phone.',
        saveButton: 'Save changes',
        savingButton: 'Saving changes…',
        contactUpdatedMessage: 'Customer details updated successfully.',
        contactConflictError:
            'This customer was modified by another action. Details have been refreshed. Please review before trying again.',
        updateContactFailed:
            'We could not update the customer details. Please check your connection and try again.',
        forbiddenContactError:
            'You do not have permission to update customer details.',
        invalidPassword: 'The provided password was incorrect.',
        lastOrderAt: 'Last order placed',
        name: 'Name',
        noAudit: 'No audit logs recorded for this customer.',
        noOrders: 'No orders placed yet.',
        noWalletEntries: 'No wallet transactions recorded.',
        networkError:
            'Network error. Please check your connection and try again.',
        orderNumber: 'Order',
        orderPlacedAt: 'Placed at',
        orderStatus: 'Status',
        orderTotal: 'Total',
        ordersCount: 'Total orders',
        ordersSection: 'Orders summary',
        passwordLabel: 'Password',
        passwordModalDescription:
            'For security, please enter your password to confirm updating customer status.',
        passwordModalTitle: 'Confirm your password',
        passwordPlaceholder: 'Enter your current password',
        phone: 'Phone',
        phoneUnverified: 'Unverified',
        phoneVerified: 'Verified',
        preferredLocale: 'Preferred language',
        reactivateButton: 'Reactivate customer',
        reactivateConsequence:
            'The customer will be able to log in and order again.',
        reactivateTitle: 'Reactivate customer',
        reactivating: 'Reactivating customer…',
        reasonLabel: 'Reason code',
        reasonRequired: 'Please select a reason code.',
        reasons: {
            abuse: 'Abuse / policy violation',
            account_recovery: 'Account recovery',
            chargeback: 'Chargeback / payment dispute',
            customer_request: 'Customer request',
            fraud_suspected: 'Fraud suspected',
            other_reviewed: 'Other reviewed reason',
        },
        recentOrders: 'Recent orders',
        recentWalletEntries: 'Recent wallet transactions',
        registeredAt: 'Registered at',
        statusDescription:
            'Control customer account activation and store access.',
        statusUpdated: 'Customer status updated successfully.',
        conflictTitle: 'Conflict',
        contactUpdated: 'Customer details updated',
        suspendedMessage:
            'The customer has been signed out and can no longer log in or place orders.',
        reactivatedMessage: 'The customer can log in and place orders again.',
        suspendButton: 'Suspend customer',
        suspendConsequence:
            'The customer will be signed out and cannot log in or order until reactivated.',
        suspendTitle: 'Suspend customer',
        suspending: 'Suspending customer…',
        title: 'Customer :name',
        totalSpent: 'Total spent',
        updateFailed:
            'We could not update the customer status. Please check your connection and try again.',
        walletBalance: 'Current balance',
        walletEntriesCount: 'Total transactions',
        walletSection: 'Wallet summary',
    },
    settings: {
        headTitle: 'Settings',
        title: 'Settings',
        description: 'Manage security and team members for the store admin.',
        securitySection: 'Security',
        securityDescription:
            'Two-factor authentication and account protection.',
        teamSection: 'Team',
        teamDescription:
            'Manage staff accounts, roles, and administrative access.',
        addMemberButton: 'Add team member',
        addMemberTitle: 'Grant Admin access',
        addMemberDescription:
            'Grant access to someone who already has an Arab UT account. Accounts are never created here, and no password is set.',
        addMemberEmailLabel: 'Account email',
        addMemberRoleLabel: 'Role',
        addMemberSubmit: 'Grant access',
        addMemberSubmitting: 'Granting access…',
        servicePricingSection: 'Service pricing',
        servicePricingDescription:
            'Manage pricing schedules and availability for FUT Champions and Division Rivals.',
        servicePricing: {
            futChampions: 'FUT Champions',
            rivals: 'Division Rivals',
            urgentSurcharge: 'Urgent surcharge',
            version: 'Version :version',
            lastUpdated: 'Last updated: :date',
            active: 'Available for sale',
            inactive: 'Unavailable (Off sale)',
            editPrices: 'Edit prices',
            editingPrices: 'Saving prices…',
            tableRank: 'Rank',
            tableStep: 'Promotion step',
            tablePrice: 'Price (SAR)',
            tableHalalah: 'Halalah',
            ranks: {
                '1': 'Rank 1',
                '2': 'Rank 2',
                '3': 'Rank 3',
                '4': 'Rank 4',
                '5': 'Rank 5',
                '6': 'Rank 6',
            },
            steps: {
                '7:6': 'Division 7 to 6',
                '6:5': 'Division 6 to 5',
                '5:4': 'Division 5 to 4',
                '4:3': 'Division 4 to 3',
                '3:2': 'Division 3 to 2',
                '2:1': 'Division 2 to 1',
                '1:elite': 'Division 1 to Elite',
            },
            editDialog: {
                title: 'Edit :service prices',
                description:
                    'Update the price schedule for :service. Prices must be positive integers in halalah.',
                confirm: 'Save price schedule',
                cancel: 'Cancel',
                halalahHint: ':halalah halalah = :sar',
            },
            deactivateDialog: {
                title: 'Deactivate :service?',
                description:
                    'Are you sure you want to deactivate :service? Customers will no longer be able to buy this service until it is reactivated.',
                confirm: 'Deactivate service',
                cancel: 'Cancel',
            },
            activateDialog: {
                title: 'Activate :service?',
                description:
                    'Are you sure you want to activate :service? Customers will be able to buy this service immediately.',
                confirm: 'Activate service',
                cancel: 'Cancel',
            },
            messages: {
                pricingUpdated: 'Service prices updated successfully.',
                statusUpdated: 'Service availability updated successfully.',
                conflictError:
                    'This price schedule was modified by another operator. Please review the latest prices before saving.',
                validationError:
                    'Please check the entered prices and try again.',
            },
            actions: {
                deactivate: 'Deactivate service',
                deactivating: 'Deactivating…',
                reactivate: 'Activate service',
                reactivating: 'Activating…',
            },
        },
        addStaffHint:
            'New staff members are provisioned via the command line: php artisan admin:grant-role user@example.com --role=staff',
        selfBadge: 'You',
        columns: {
            member: 'Member',
            name: 'Name',
            email: 'Email',
            role: 'Role',
            status: 'Status',
            mfa: 'MFA',
            joined: 'Joined',
            actions: 'Actions',
        },
        roles: {
            admin: 'Admin',
            staff: 'Staff',
        },
        status: {
            active: 'Active',
            inactive: 'Inactive',
        },
        mfa: {
            confirmed: 'Confirmed',
            pending: 'Pending',
        },
        actions: {
            applyRole: 'Apply',
            applyingRole: 'Applying…',
            changeRole: 'Change role',
            deactivate: 'Deactivate',
            deactivating: 'Deactivating…',
            reactivate: 'Reactivate',
            reactivating: 'Reactivating…',
            roleSelectLabel: 'Role for :name',
        },
        roleDialog: {
            title: 'Change staff role',
            description:
                'Are you sure you want to change the role of :name from :from to :to?',
            confirm: 'Change role',
            cancel: 'Cancel',
        },
        deactivateDialog: {
            title: 'Deactivate staff member',
            description:
                'Are you sure you want to deactivate :name? They will be signed out immediately and lose all access to the admin dashboard.',
            confirm: 'Deactivate account',
            cancel: 'Cancel',
        },
        reactivateDialog: {
            title: 'Reactivate staff member',
            description:
                'Are you sure you want to reactivate :name? They will be able to sign in and access the admin dashboard again.',
            confirm: 'Reactivate account',
            cancel: 'Cancel',
        },
        messages: {
            roleUpdated: 'Staff role updated successfully.',
            statusUpdated: 'Staff status updated successfully.',
            conflictError:
                'This account was modified by another action. Please review the latest details before trying again.',
            genericError:
                'We could not complete the request. Check your connection and try again.',
            networkError:
                'Network error. Please check your connection and try again.',
            forbiddenError:
                'You do not have permission to perform this action.',
            grantSucceeded:
                'Admin access granted. They sign in with their existing password and set up two-factor authentication before Admin opens.',
            grantNoSuchAccount:
                'No account exists for that email address. Ask them to sign up first, then grant access here.',
            grantSelf: 'You cannot change your own role.',
            grantAlreadyGranted: 'That account already has this role.',
            grantInactiveAccount:
                'Reactivate that account before granting Admin access.',
            lastAdminError:
                'Cannot modify or deactivate the last active Admin account.',
        },
    },
    products: {
        actions: 'Actions',
        allArchived: 'Active and archived',
        allAuthorities: 'All authorities',
        allServices: 'All services',
        allSources: 'All sources',
        allVisibilities: 'All visibilities',
        archivedActive: 'Active only',
        archivedArchived: 'Archived only',
        authority: 'Authority',
        authorityAutomation: 'Automation',
        authorityManual: 'Manual',
        clearSearch: 'Clear search',
        columns: 'Columns',
        createdAt: 'Created at',
        description: 'View and manage store catalog products and services.',
        errorTitle: 'Products unavailable',
        filterArchived: 'Filter by archived status',
        filterAuthority: 'Filter by authority',
        filterService: 'Filter by service',
        filterSource: 'Filter by source',
        filterVisibility: 'Filter by visibility',
        filters: 'Filters',
        firstPage: 'First page',
        headTitle: 'Products',
        lastPage: 'Last page',
        loadFailed:
            'We could not update the products list. Check your connection and try again.',
        loading: 'Loading products…',
        name: 'Name',
        next: 'Next',
        noProducts: 'No products found.',
        noProductsMatching: 'No products match your filter criteria.',
        of: 'of',
        page: 'Page',
        perPage: 'Per page',
        previous: 'Previous',
        product: 'Product',
        resetFilters: 'Reset filters',
        results: 'results',
        searchButton: 'Search',
        searchLabel: 'Search products',
        searchPlaceholder: 'Search by name, slug, or SKU…',
        selectAll: 'Select all rows on this page',
        selectRow: 'Select row',
        selectedRows: ':count of :total row(s) selected',
        service: 'Service',
        showing: 'Showing',
        slug: 'Slug',
        sortAscending: 'sorted ascending',
        sortBy: 'Sort by :column',
        sortDescending: 'sorted descending',
        sortOrder: 'Sort order',
        source: 'Source',
        sourceManual: 'Manual (Internal)',
        tableLabel: 'Products list',
        title: 'Products',
        to: 'to',
        toggleColumns: 'Toggle columns',
        updatedAt: 'Updated at',
        variants: 'Variants',
        variantsCount: 'Variants',
        viewDetail: 'View product',
        visibility: 'Visibility',
        visibilityHidden: 'Hidden',
        visibilityVisible: 'Visible',
    },
    productDetail: {
        action: 'Action',
        authorityAutomation: 'Automation',
        authorityManual: 'Manual',
        variantsCount: 'variants',
        active: 'Active',
        activeFlag: 'Active',
        actor: 'Staff member',
        altAr: 'Arabic alt text',
        altEn: 'English alt text',
        archived: 'Archived',
        auditSection: 'Staff audit activity',
        authority: 'Authority',
        automationSection: 'Automation snapshot history',
        backToProducts: 'Back to products',
        cancelButton: 'Cancel',
        category: 'Category',
        completedAt: 'Completed at',
        confirmPasswordButton: 'Confirm password',
        confirmingPassword: 'Verifying password…',
        conflictError:
            'This product was modified by another action. Details have been refreshed. Please review before trying again.',
        conflictTitle: 'Conflict',
        date: 'Date',
        descriptionArLabel: 'Arabic description',
        descriptionEnLabel: 'English description',
        descriptionsSection: 'Descriptions',
        disk: 'Storage disk',
        editButton: 'Edit product',
        editDescription:
            'Update product name, descriptions, visibility, and sort order.',
        editTitle: 'Edit manual product',
        forbiddenError:
            'You do not have permission to manage catalog products.',
        headTitle: 'Product :name',
        hidden: 'Hidden',
        inactiveFlag: 'Inactive',
        invalidPassword: 'The provided password was incorrect.',
        isVisibleHelp:
            'When enabled, this product is visible to customers on the storefront.',
        isVisibleLabel: 'Visible in store',
        lastSnapshot: 'Last snapshot run',
        lastUpdated: 'Last updated',
        manualSource: 'Manual (Store Catalog)',
        market: 'Market',
        mediaSection: 'Media assets',
        nameArLabel: 'Arabic name',
        nameEnLabel: 'English name',
        networkError:
            'Network error. Please check your connection and try again.',
        noAudit: 'No audit logs recorded for this product.',
        noAutomationHistory:
            'No automation sync history recorded for this product.',
        noCategory: 'No category',
        noDescriptionAr: 'No Arabic description provided.',
        noDescriptionEn: 'No English description provided.',
        noMedia: 'No media assets attached to this product.',
        noVariants: 'No variants for this product.',
        notEditableError: 'Automation products cannot be edited manually.',
        outcome: 'Item outcome',
        passwordLabel: 'Password',
        passwordModalDescription:
            'For security, please enter your password to confirm updating product details.',
        passwordModalTitle: 'Confirm your password',
        passwordPlaceholder: 'Enter your current password',
        path: 'Path',
        platform: 'Platform',
        price: 'Price',
        priceVersion: 'Price version',
        pricesReadOnlyNotice:
            'Variant prices are versioned and managed through price proposal runs. Price editing is read-only.',
        productInformation: 'Product information',
        productUpdated: 'Product updated',
        productUpdatedMessage: 'Product details updated successfully.',
        quantity: 'Quantity (k)',
        readOnlyBadge: 'Read-only',
        readOnlyNotice:
            'This product is managed by automation snapshot runs and is read-only. Manual edits are disabled to prevent snapshots from overwriting changes.',
        registeredAt: 'Created at',
        runId: 'Run ID',
        runStatus: 'Run status',
        salePrice: 'Sale price',
        saveButton: 'Save changes',
        savingButton: 'Saving changes…',
        serviceType: 'Service type',
        sku: 'SKU',
        slug: 'Slug',
        sortOrder: 'Sort order',
        sortOrderHelp:
            'Lower numbers appear earlier in catalog listings (0 is highest priority).',
        sortOrderLabel: 'Sort order',
        source: 'Source',
        startedAt: 'Started at',
        status: 'Status',
        syncedAt: 'Synced at',
        title: 'Product :name',
        updateFailed:
            'We could not update the product. Please check your connection and try again.',
        variantsSection: 'Variants & pricing',
        visibility: 'Visibility',
        visible: 'Visible',
    },
};

export const sampleAdminOrderRows = [
    {
        id: '01K5ADM1N00000000000000001',
        orderNumber: 'AUT-1001',
        customer: {
            id: '01K5CUST00000000000000001',
            name: 'Saud Al-Otaibi',
            email: 'saud@example.test',
            phone: '+966500000001',
        },
        status: 'received',
        serviceTypes: ['coins'],
        platforms: ['playstation'],
        itemCount: 1,
        latestPaymentStatus: 'paid',
        total: {
            amountMinor: '15000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T10:00:00Z',
    },
    {
        id: '01K5ADM1N00000000000000002',
        orderNumber: 'AUT-1002',
        customer: {
            id: '01K5CUST00000000000000002',
            name: 'Fahad Al-Harbi',
            email: 'fahad@example.test',
            phone: null,
        },
        status: 'in_progress',
        serviceTypes: ['sbc', 'rivals'],
        platforms: ['pc'],
        itemCount: 2,
        latestPaymentStatus: 'paid',
        total: {
            amountMinor: '35000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T11:30:00Z',
    },
    {
        id: '01K5ADM1N00000000000000003',
        orderNumber: 'AUT-1003',
        customer: {
            id: '01K5CUST00000000000000003',
            name: 'Tariq Al-Ghamdi',
            email: 'tariq@example.test',
            phone: '+966500000003',
        },
        status: 'pending_payment',
        serviceTypes: ['fut_champions'],
        platforms: ['xbox'],
        itemCount: 1,
        latestPaymentStatus: null,
        total: {
            amountMinor: '20000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T14:00:00Z',
    },
];

export const sampleAdminFilterOptions = {
    statuses: [
        { value: 'pending_payment', label: 'Pending payment' },
        { value: 'received', label: 'Received' },
        { value: 'in_progress', label: 'In progress' },
        { value: 'waiting_for_customer', label: 'Waiting for customer' },
        { value: 'completed', label: 'Completed' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'refunded', label: 'Refunded' },
    ],
    services: [
        { value: 'coins', label: 'Coins' },
        { value: 'sbc', label: 'SBC' },
        { value: 'objectives', label: 'Objectives' },
        { value: 'rivals', label: 'Division Rivals' },
        { value: 'fut_champions', label: 'FUT Champions' },
    ],
    platforms: [
        { value: 'playstation', label: 'PlayStation' },
        { value: 'xbox', label: 'Xbox' },
        { value: 'pc', label: 'PC' },
    ],
    paymentStatuses: [
        { value: 'pending', label: 'Pending' },
        { value: 'authorized', label: 'Authorized' },
        { value: 'paid', label: 'Paid' },
        { value: 'failed', label: 'Failed' },
        { value: 'partially_refunded', label: 'Partially refunded' },
        { value: 'refunded', label: 'Refunded' },
    ],
    perPageOptions: [15, 25, 50, 100],
};

export const sampleAdminPagination = {
    currentPage: 1,
    lastPage: 3,
    perPage: 15 as const,
    total: 35,
    from: 1,
    to: 15,
};

export const sampleAdminOrderDetail = {
    id: '01K5ADM1N00000000000000001',
    orderNumber: 'AUT-1001',
    status: 'received',
    currency: 'SAR',
    placedAt: '2026-08-20T10:00:00Z',
    paidAt: '2026-08-20T10:05:00Z',
    completedAt: null,
    cancelledAt: null,
    customer: {
        id: '01K5CUST00000000000000001',
        name: 'Saud Al-Otaibi',
        email: 'saud@example.test',
        phone: '+966500000001',
    },
    money: {
        subtotal: { amountMinor: '15000', currency: 'SAR' as const },
        discount: { amountMinor: '0', currency: 'SAR' as const },
        wallet: { amountMinor: '0', currency: 'SAR' as const },
        payment: { amountMinor: '15000', currency: 'SAR' as const },
        total: { amountMinor: '15000', currency: 'SAR' as const },
    },
    items: [
        {
            id: '01K5ITEM00000000000000001',
            name: 'Coins Service',
            serviceType: 'coins',
            platform: 'playstation',
            quantity: 1,
            unitPrice: { amountMinor: '15000', currency: 'SAR' as const },
            subtotal: { amountMinor: '15000', currency: 'SAR' as const },
            discount: { amountMinor: '0', currency: 'SAR' as const },
            total: { amountMinor: '15000', currency: 'SAR' as const },
            status: 'received',
            configuration: null,
            hasSecret: false,
            maskedSummary: null,
            statusHistory: [],
        },
    ],
    payments: [
        {
            id: '01K5PAY00000000000000001',
            status: 'paid',
            currency: 'SAR',
            amount: { amountMinor: '15000', currency: 'SAR' as const },
            capturedAmount: { amountMinor: '15000', currency: 'SAR' as const },
            refundedAmount: { amountMinor: '0', currency: 'SAR' as const },
            paidAt: '2026-08-20T10:05:00Z',
            createdAt: '2026-08-20T10:00:00Z',
        },
    ],
    refunds: [],
    discounts: [],
    statusHistory: [
        {
            id: '01K5HIST00000000000000001',
            status: 'received',
            source: 'system',
            previousStatus: 'pending_payment',
            newStatus: 'received',
            createdAt: '2026-08-20T10:05:00Z',
            actor: null,
        },
    ],
    auditContext: [
        {
            id: '01K5AUD00000000000000001',
            action: 'orders.viewed',
            actor: { name: 'Operations Owner', role: 'admin' },
            createdAt: '2026-08-20T10:10:00Z',
        },
    ],
};

export const sampleAdminCustomerRows = [
    {
        id: '01K5CUST00000000000000001',
        number: 'CUS-ROW001',
        name: 'Saud Al-Otaibi',
        email: 'saud@example.test',
        phone: '+966500000001',
        isActive: true,
        createdAt: '2026-08-15T10:00:00Z',
        ordersCount: 3,
        lastOrderAt: '2026-08-20T10:00:00Z',
        totalSpent: {
            amountMinor: '45000',
            currency: 'SAR' as const,
        },
        walletBalance: {
            amountMinor: '12000',
            currency: 'SAR' as const,
        },
    },
    {
        id: '01K5CUST00000000000000002',
        number: 'CUS-ROW002',
        name: 'Fahad Al-Harbi',
        email: 'fahad@example.test',
        phone: null,
        isActive: false,
        createdAt: '2026-08-16T12:00:00Z',
        ordersCount: 1,
        lastOrderAt: '2026-08-18T14:30:00Z',
        totalSpent: {
            amountMinor: '15000',
            currency: 'SAR' as const,
        },
        walletBalance: {
            amountMinor: '0',
            currency: 'SAR' as const,
        },
    },
];

export const sampleAdminCustomerFilterOptions = {
    statuses: [
        { value: 'active', label: 'Active' },
        { value: 'suspended', label: 'Suspended' },
    ],
    perPageOptions: [15, 25, 50, 100],
};

export const sampleAdminCustomerDetail = {
    id: '01K5CUST00000000000000001',
    number: 'CUS-7K4QXM',
    name: 'Saud Al-Otaibi',
    firstName: 'Saud',
    lastName: 'Al-Otaibi',
    email: 'saud@example.test',
    phone: '+966500000001',
    preferredLocale: 'ar',
    isActive: true,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
    emailVerifiedAt: '2026-08-15T10:05:00Z',
    phoneVerifiedAt: '2026-08-15T10:06:00Z',
    ordersSummary: {
        ordersCount: 3,
        totalSpent: { amountMinor: '45000', currency: 'SAR' as const },
        lastOrderAt: '2026-08-20T10:00:00Z',
    },
    recentOrders: [
        {
            id: '01K5ORD00000000000000001',
            orderNumber: 'AUT-1001',
            status: 'completed',
            total: { amountMinor: '15000', currency: 'SAR' as const },
            placedAt: '2026-08-20T10:00:00Z',
        },
    ],
    walletSummary: {
        balance: { amountMinor: '12000', currency: 'SAR' as const },
        entriesCount: 2,
    },
    recentWalletEntries: [
        {
            id: '01K5WLT00000000000000001',
            type: 'credit',
            direction: 'credit' as const,
            amount: { amountMinor: '12000', currency: 'SAR' as const },
            createdAt: '2026-08-19T08:00:00Z',
            reference: 'PROMO-2026',
        },
    ],
    recentAuditLogs: [
        {
            id: '01K5AUD00000000000000002',
            action: 'customers.suspended',
            actor: { name: 'Operations Owner', role: 'admin' },
            createdAt: '2026-08-18T10:00:00Z',
            metadata: {
                reason_code: 'fraud_suspected',
                case_reference: 'CASE-001',
                previous_active: true,
                new_active: false,
            },
        },
    ],
};

export const sampleAdminTeamData: AdminTeamData = {
    currentUserId: '01K5ADM1N00000000000000001',
    members: [
        {
            id: '01K5ADM1N00000000000000001',
            name: 'Operations Owner',
            email: 'owner@arabut.test',
            role: 'admin',
            isActive: true,
            mfaConfirmed: true,
            createdAt: '2026-08-01T08:00:00Z',
        },
        {
            id: '01K5ADM1N00000000000000002',
            name: 'Staff Operator',
            email: 'staff@arabut.test',
            role: 'staff',
            isActive: true,
            mfaConfirmed: false,
            createdAt: '2026-08-05T09:00:00Z',
        },
        {
            id: '01K5ADM1N00000000000000003',
            name: 'Inactive Admin',
            email: 'inactive@arabut.test',
            role: 'admin',
            isActive: false,
            mfaConfirmed: true,
            createdAt: '2026-08-10T10:00:00Z',
        },
    ],
};

export const sampleAdminTeamUrls: AdminTeamUrls = {
    grantUrl: '/admin/api/team/grants',
    roleUrlTemplate: '/admin/api/team/__ID__/role',
    statusUrlTemplate: '/admin/api/team/__ID__/status',
};

export const sampleAdminServicePricingData: AdminServicePricingData = {
    schedules: [
        {
            serviceType: 'fut_champions',
            version: 1,
            isActive: true,
            updatedAt: '2026-08-20T10:00:00Z',
            configuration: {
                ranks: {
                    '1': 22000,
                    '2': 19000,
                    '3': 17000,
                    '4': 15000,
                    '5': 13000,
                    '6': 10000,
                },
                urgent_surcharge_halalah: 4000,
            },
        },
        {
            serviceType: 'rivals',
            version: 1,
            isActive: true,
            updatedAt: '2026-08-20T11:00:00Z',
            configuration: {
                steps: {
                    '7:6': 11000,
                    '6:5': 12000,
                    '5:4': 13000,
                    '4:3': 14000,
                    '3:2': 15000,
                    '2:1': 16000,
                    '1:elite': 17000,
                },
            },
        },
    ],
};

export const sampleAdminProductRows = [
    {
        id: '01K5PROD00000000000000001',
        slug: 'fc-26-coins-ps5',
        name: 'FC 26 Coins PS5',
        nameAr: 'كوينز فيفا 26 بلايستيشن 5',
        nameEn: 'FC 26 Coins PS5',
        serviceType: 'coins',
        authority: 'manual' as const,
        source: null,
        isVisible: true,
        sortOrder: 1,
        isArchived: false,
        variantsCount: 3,
        createdAt: '2026-08-15T10:00:00Z',
        updatedAt: '2026-08-20T10:00:00Z',
    },
    {
        id: '01K5PROD00000000000000002',
        slug: 'fc-26-sbc-service',
        name: 'FC 26 SBC Service',
        nameAr: 'خدمة تحديات التشكيلات فيفا 26',
        nameEn: 'FC 26 SBC Service',
        serviceType: 'sbc',
        authority: 'automation' as const,
        source: {
            name: 'Provider Alpha',
            key: 'provider_alpha',
        },
        isVisible: true,
        sortOrder: 2,
        isArchived: false,
        variantsCount: 1,
        createdAt: '2026-08-16T10:00:00Z',
        updatedAt: '2026-08-21T10:00:00Z',
    },
    {
        id: '01K5PROD00000000000000003',
        slug: 'fc-25-coins-xbox',
        name: 'FC 25 Coins Xbox',
        nameAr: 'كوينز فيفا 25 إكس بوكس',
        nameEn: 'FC 25 Coins Xbox',
        serviceType: 'coins',
        authority: 'manual' as const,
        source: null,
        isVisible: false,
        sortOrder: 10,
        isArchived: true,
        variantsCount: 2,
        createdAt: '2026-08-01T10:00:00Z',
        updatedAt: '2026-08-10T10:00:00Z',
    },
];

export const sampleAdminProductFilterOptions = {
    services: [
        { value: 'coins', label: 'Coins' },
        { value: 'sbc', label: 'SBC' },
        { value: 'draft', label: 'Draft' },
    ],
    authorities: [
        { value: 'manual', label: 'Manual' },
        { value: 'automation', label: 'Automation' },
    ],
    sources: [
        { value: 'manual', label: 'Manual (Internal)' },
        { value: 'provider_alpha', label: 'Provider Alpha' },
    ],
    visibilities: [
        { value: 'visible', label: 'Visible' },
        { value: 'hidden', label: 'Hidden' },
    ],
    archived: [
        { value: 'active', label: 'Active only' },
        { value: 'archived', label: 'Archived only' },
    ],
    perPageOptions: [15, 25, 50, 100],
};

export const sampleAdminProductDetail = {
    id: '01K5PROD00000000000000001',
    slug: 'fc-26-coins-ps5',
    name: 'FC 26 Coins PS5',
    nameAr: 'كوينز فيفا 26 بلايستيشن 5',
    nameEn: 'FC 26 Coins PS5',
    descriptionAr: 'كوينز آمنة ومضمونة وبأفضل الأسعار.',
    descriptionEn: 'Safe and guaranteed coins with the best prices.',
    serviceType: 'coins',
    authority: 'manual' as const,
    isEditable: true,
    isVisible: true,
    sortOrder: 1,
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
    category: {
        id: '01K5CAT00000000000000001',
        name: 'Coins',
        slug: 'coins',
    },
    source: null,
    variants: [
        {
            id: '01K5VAR00000000000000001',
            sku: 'COINS-PS5-100K',
            serviceType: 'coins',
            platform: 'playstation_5',
            market: 'sa',
            authority: 'manual',
            nameAr: '100 ألف كوينز',
            nameEn: '100k Coins',
            quantityK: 100,
            price: { amountMinor: '3500', currency: 'SAR' as const },
            salePrice: { amountMinor: '3000', currency: 'SAR' as const },
            priceVersion: 1,
            configuration: null,
            isActive: true,
            createdAt: '2026-08-15T10:00:00Z',
            updatedAt: '2026-08-15T10:00:00Z',
        },
        {
            id: '01K5VAR00000000000000002',
            sku: 'COINS-PS5-500K',
            serviceType: 'coins',
            platform: 'playstation_5',
            market: 'sa',
            authority: 'manual',
            nameAr: '500 ألف كوينز',
            nameEn: '500k Coins',
            quantityK: 500,
            price: { amountMinor: '15000', currency: 'SAR' as const },
            salePrice: null,
            priceVersion: 2,
            configuration: null,
            isActive: true,
            createdAt: '2026-08-15T10:00:00Z',
            updatedAt: '2026-08-18T10:00:00Z',
        },
    ],
    media: [
        {
            id: '01K5MED00000000000000001',
            disk: 'public',
            path: 'products/fc26-coins-cover.png',
            altAr: 'غلاف كوينز فيفا 26',
            altEn: 'FC 26 Coins Cover',
            sortOrder: 1,
        },
    ],
    automation: null,
    recentAuditLogs: [
        {
            id: '01K5AUD00000000000000001',
            action: 'products.updated',
            actor: { name: 'Operations Owner', role: 'admin' },
            createdAt: '2026-08-20T10:00:00Z',
            metadata: {
                product_changed: ['sort_order'],
                product_previous: { sort_order: 5 },
                product_new: { sort_order: 1 },
            },
        },
    ],
};

export const sampleAdminServicePricingUrls: AdminServicePricingUrls = {
    updateUrlTemplate: '/admin/api/settings/service-pricing/__SERVICE__',
    statusUrlTemplate: '/admin/api/settings/service-pricing/__SERVICE__/status',
};

export const sampleAdminAutomationProductDetail = {
    id: '01K5PROD00000000000000002',
    slug: 'fc-26-sbc-service',
    name: 'FC 26 SBC Service',
    nameAr: 'خدمة تحديات التشكيلات فيفا 26',
    nameEn: 'FC 26 SBC Service',
    descriptionAr: 'حل تحديات التشكيلات آلياً وبأعلى سرعة.',
    descriptionEn: 'Automated SBC completion with maximum speed.',
    serviceType: 'sbc',
    authority: 'automation' as const,
    isEditable: false,
    isVisible: true,
    sortOrder: 2,
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-21T10:00:00Z',
    category: {
        id: '01K5CAT00000000000000002',
        name: 'SBC',
        slug: 'sbc',
    },
    source: {
        id: '01K5SRC00000000000000001',
        key: 'provider_alpha',
        name: 'Provider Alpha',
        authority: 'automation',
    },
    variants: [
        {
            id: '01K5VAR00000000000000003',
            sku: 'SBC-POTM-PREMIER',
            serviceType: 'sbc',
            platform: 'playstation_5',
            market: 'global',
            authority: 'automation',
            nameAr: 'تحدي لاعب الشهر للدوري الإنجليزي',
            nameEn: 'Premier League POTM SBC',
            quantityK: null,
            price: { amountMinor: '5000', currency: 'SAR' as const },
            salePrice: null,
            priceVersion: 1,
            configuration: { difficulty: 'hard' },
            isActive: true,
            createdAt: '2026-08-16T10:00:00Z',
            updatedAt: '2026-08-16T10:00:00Z',
        },
    ],
    media: [],
    automation: {
        runId: 'RUN-2026-08-21-001',
        status: 'completed',
        outcome: 'applied',
        completedAt: '2026-08-21T10:05:00Z',
        startedAt: '2026-08-21T10:00:00Z',
        error: null,
        syncedAt: '2026-08-21T10:05:00Z',
    },
    recentAuditLogs: null,
};
