import type { AdminTranslations } from '@/types/admin';

export const englishAdminUi: AdminTranslations = {
    brand: 'Arab UT',
    common: {
        cancel: 'Cancel',
        logout: 'Log out',
        noData: 'No data',
        retry: 'Try again',
    },
    navigation: {
        close: 'Close Admin navigation',
        open: 'Open Admin navigation',
        orders: 'Orders',
        overview: 'Overview',
        security: 'MFA Security',
    },
    overview: {
        capturedRevenue: 'Captured revenue',
        description:
            'A focused summary of orders and payments that need attention.',
        failedPayments: 'Failed payments',
        failedRefunds: 'Failed refunds',
        headTitle: 'Operational overview',
        inProgressOrders: 'Orders in progress',
        noAudit: 'There is no recent Admin activity.',
        noUnresolved: 'There are no unresolved orders.',
        oldestUnresolved: 'Oldest unresolved order',
        pendingPayments: 'Pending payments',
        range7: 'Last 7 days',
        range30: 'Last 30 days',
        receivedOrders: 'Received orders',
        recentAudit: 'Recent Admin activity',
        title: 'Operations dashboard',
        waitingForCustomer: 'Waiting for customer',
        totalOrders: 'Total placed orders',
        newCustomers: 'New customers',
        needsAttention: 'Needs attention',
        previousPeriod: 'vs. previous period',
        newThisPeriod: 'New this period',
        noChange: 'No change',
        revenueTrendTitle: 'Captured revenue trend',
        revenueTrendDescription:
            'Daily gross captured revenue over the selected window',
        orderDistributionTitle: 'Order status distribution',
        orderDistributionDescription:
            'All orders placed in the selected window by status',
        revenueTableAria: 'Daily captured revenue summary',
        date: 'Date',
        revenue: 'Revenue',
        status: 'Status',
        count: 'Count',
        noRevenue: 'No captured revenue in this period.',
        noOrdersInPeriod: 'No orders placed in this period.',
        recentOrdersTitle: 'Recent placed orders',
        recentOrdersDescription:
            'Latest orders placed during the selected window',
        orderNumber: 'Order',
        orderTotal: 'Total',
        orderPlacedAt: 'Placed at',
        noRecentOrders: 'There are no recent orders in this period.',
        attentionRailTitle: 'Operational focus',
    },
    orders: {
        allPaymentStatuses: 'All payment statuses',
        allPlatforms: 'All platforms',
        allServices: 'All services',
        allStatuses: 'All statuses',
        clearSearch: 'Clear search',
        columns: 'Columns',
        customer: 'Customer',
        dateFrom: 'Date from',
        dateTo: 'Date to',
        description:
            'View and filter all customer orders across services and platforms.',
        filterPayment: 'Filter by payment status',
        filterPlatform: 'Filter by platform',
        filterService: 'Filter by service',
        filterStatus: 'Filter by status',
        headTitle: 'Orders',
        items: 'Items',
        loading: 'Loading orders…',
        errorTitle: 'Orders unavailable',
        loadFailed:
            'We could not update the orders list. Check your connection and try again.',
        tableLabel: 'Orders list',
        firstPage: 'First page',
        lastPage: 'Last page',
        next: 'Next',
        noOrders: 'No orders found.',
        noOrdersMatching: 'No orders match your filter criteria.',
        noPayment: 'No payment',
        of: 'of',
        order: 'Order',
        page: 'Page',
        payment: 'Payment',
        perPage: 'Per page',
        placedAt: 'Placed at',
        platform: 'Platform',
        platforms: {
            pc: 'PC',
            playstation: 'PlayStation',
            xbox: 'Xbox',
        },
        previous: 'Previous',
        resetFilters: 'Reset filters',
        results: 'results',
        searchButton: 'Search',
        searchLabel: 'Search orders',
        searchPlaceholder: 'Search by order #, public ID, email, or phone…',
        service: 'Service',
        selectAll: 'Select all rows on this page',
        selectRow: 'Select row',
        selectedRows: ':count of :total row(s) selected',
        services: {
            coins: 'Coins',
            fut_champions: 'FUT Champions',
            objectives: 'Objectives',
            rivals: 'Division Rivals',
            sbc: 'SBC',
        },
        showing: 'Showing',
        sortBy: 'Sort by :column',
        sortAscending: 'sorted ascending',
        sortDescending: 'sorted descending',
        status: 'Status',
        title: 'Orders',
        to: 'to',
        toggleColumns: 'Toggle columns',
        total: 'Total',
    },
    orderDetail: {
        headTitle: 'Order :number',
        title: 'Order :number',
        backToOrders: 'Back to orders',
        customerSection: 'Customer information',
        paymentSection: 'Payment & breakdown',
        itemsSection: 'Order items',
        historySection: 'Status history',
        auditSection: 'Admin audit activity',
        transitionsTitle: 'Change order status',
        transitionsDescription:
            'Transition this order to a valid next lifecycle state.',
        noHistory: 'No status history recorded.',
        noAudit: 'No audit logs recorded for this order.',
        noItems: 'No items in this order.',
        noDiscounts: 'No discounts applied.',
        noPayments: 'No payments recorded.',
        noRefunds: 'No refunds recorded.',
        customerName: 'Customer name',
        customerEmail: 'Email',
        customerPhone: 'Phone',
        subtotal: 'Subtotal',
        discount: 'Discount',
        wallet: 'Wallet balance applied',
        payment: 'Payment collected',
        total: 'Total',
        currency: 'Currency',
        placedAt: 'Placed at',
        paidAt: 'Paid at',
        completedAt: 'Completed at',
        cancelledAt: 'Cancelled at',
        item: 'Item',
        service: 'Service',
        platform: 'Platform',
        quantity: 'Quantity',
        unitPrice: 'Unit price',
        status: 'Status',
        source: 'Source',
        actor: 'Staff member',
        date: 'Date',
        changeStatusTo: 'Change status to :status',
        confirmModalTitle: 'Confirm status change',
        confirmModalDescription:
            'Are you sure you want to change order :number to :status? This will update active order items and record a staff audit log.',
        confirmCancelDescription:
            'Are you sure you want to cancel order :number? This action is permanent and will cancel all active items in this order.',
        confirmCompleteDescription:
            'Are you sure you want to complete order :number? This will mark matching active items as completed.',
        confirmButton: 'Confirm transition',
        cancelButton: 'Cancel',
        updating: 'Updating status…',
        statusUpdated: 'Order status updated successfully.',
        conflictError:
            'This order was modified by another action. Current status is :status. Please review before proceeding.',
        transitionFailed:
            'We could not update the order status. Please check your connection and try again.',
        forbiddenTransition:
            'You do not have permission to perform this status transition.',
        noTransitionsAvailable:
            'No further status transitions are available for this order.',
        secrets: {
            revealButton: 'Reveal credentials',
            hideButton: 'Hide credentials',
            showButton: 'Show credentials',
            copyButton: 'Copy',
            copied: 'Copied to clipboard',
            closeButton: 'Close credentials',
            cancelButton: 'Cancel',
            confirmReveal: 'Confirm reveal',
            revealing: 'Revealing credentials…',
            purposeLabel: 'Access purpose',
            purposeRequired:
                'Please select a purpose for accessing credentials.',
            purposes: {
                fulfillment: 'Order fulfillment',
                customer_support: 'Customer support inquiry',
                order_review: 'Order review or verification',
                incident_investigation: 'Incident investigation',
            },
            caseReferenceLabel: 'Case reference (optional)',
            caseReferencePlaceholder: 'e.g. TICKET-1234 or CR-5678',
            caseReferenceHelp:
                'Alphanumeric and . _ : - characters only, up to 64 characters.',
            purgedNotice:
                'Credentials for this item have been purged and are no longer available.',
            purgedBadge: 'Purged',
            revealedBadge: 'Revealed',
            maskedSummaryTitle: 'Stored credentials',
            revealedCredentialsTitle: 'Decrypted credentials',
            passwordModalTitle: 'Confirm your password',
            passwordModalDescription:
                'For security, please enter your password to confirm access to order credentials.',
            passwordLabel: 'Password',
            passwordPlaceholder: 'Enter your current password',
            confirmPasswordButton: 'Confirm password',
            confirmingPassword: 'Verifying password…',
            invalidPassword: 'The provided password was incorrect.',
            genericError: 'Unable to reveal credentials. Please try again.',
            networkError:
                'Network error. Please check your connection and try again.',
            forbiddenError: 'You do not have permission to view credentials.',
            copyFallbackSuccess: 'Copied',
            copyFallbackFailed: 'Unable to copy to clipboard',
        },
    },
    statuses: {
        authorized: 'Authorized',
        cancelled: 'Cancelled',
        completed: 'Completed',
        failed: 'Failed',
        in_progress: 'In progress',
        paid: 'Paid',
        partially_refunded: 'Partially refunded',
        pending: 'Pending',
        pending_payment: 'Pending payment',
        received: 'Received',
        refunded: 'Refunded',
        waiting_for_customer: 'Waiting for customer',
    },
    mfa: {
        accessDenied:
            'Your account is no longer eligible to manage Admin security.',
        configured: 'Two-factor authentication is on',
        configuredDescription: 'Your account is protected and can enter Admin.',
        confirm: 'Confirm two-factor setup',
        confirmCode: 'Authenticator code',
        confirmPasswordAgain: 'Confirm password',
        confirmRegenerate: 'Replace recovery codes',
        confirming: 'Confirming the code…',
        description:
            'Use an authenticator app to protect your account before entering Admin.',
        enable: 'Start two-factor setup',
        enabling: 'Creating your setup code…',
        eyebrow: 'Admin security',
        failed: 'We could not complete the security request. Your account settings were not changed.',
        headTitle: 'Protect your Admin account',
        hideRecoveryCodes: 'Hide recovery codes',
        invalidCode:
            'That code is invalid or expired. Check your authenticator app and try again.',
        openAccountSecurity: 'Open account security',
        passwordConfirmationExpired:
            'Your password confirmation expired. Confirm it again to continue.',
        qrAlt: 'QR code for adding Arab UT to an authenticator app',
        rateLimited:
            'Too many attempts were sent. Wait one minute before trying again.',
        recoveryTitle: 'Recovery codes',
        recoveryWarning:
            'Keep these codes somewhere safe. Each code can be used only once.',
        regenerateDescription:
            'Your current codes will stop working immediately. Be ready to save the new codes.',
        regenerateRecoveryCodes: 'Create new recovery codes',
        regenerateTitle: 'Replace recovery codes?',
        regenerating: 'Creating new codes…',
        retryAfterWait: 'Reload the page after one minute',
        returnToStore: 'Return to the store',
        scanDescription:
            'Open your authenticator app and scan the code. Then enter the 6-digit code it shows.',
        scanTitle: 'Scan the QR code',
        sessionExpired: 'Your session expired. Sign in again to continue.',
        setupPassword: 'Set a password first',
        setupPasswordDescription:
            'Add a password in account security, then return to finish two-factor setup.',
        showRecoveryCodes: 'Show recovery codes',
        signIn: 'Sign in again',
        startDescription:
            'We will create a QR code for this account. Scan it in your authenticator app, then confirm the code it shows.',
        startTitle: 'Connect your authenticator app',
        title: 'Set up two-factor authentication',
    },
};

export const sampleAdminOrderRows = [
    {
        id: '01K5ADM1N00000000000000001',
        orderNumber: 'AUT-1001',
        customer: {
            id: '01K5CUST00000000000000001',
            name: 'Saud Al-Otaibi',
            email: 'saud@example.test',
            phone: '+966500000001',
        },
        status: 'received',
        serviceTypes: ['coins'],
        platforms: ['playstation'],
        itemCount: 1,
        latestPaymentStatus: 'paid',
        total: {
            amountMinor: '15000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T10:00:00Z',
    },
    {
        id: '01K5ADM1N00000000000000002',
        orderNumber: 'AUT-1002',
        customer: {
            id: '01K5CUST00000000000000002',
            name: 'Fahad Al-Harbi',
            email: 'fahad@example.test',
            phone: null,
        },
        status: 'in_progress',
        serviceTypes: ['sbc', 'rivals'],
        platforms: ['pc'],
        itemCount: 2,
        latestPaymentStatus: 'paid',
        total: {
            amountMinor: '35000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T11:30:00Z',
    },
    {
        id: '01K5ADM1N00000000000000003',
        orderNumber: 'AUT-1003',
        customer: {
            id: '01K5CUST00000000000000003',
            name: 'Tariq Al-Ghamdi',
            email: 'tariq@example.test',
            phone: '+966500000003',
        },
        status: 'pending_payment',
        serviceTypes: ['fut_champions'],
        platforms: ['xbox'],
        itemCount: 1,
        latestPaymentStatus: null,
        total: {
            amountMinor: '20000',
            currency: 'SAR' as const,
        },
        placedAt: '2026-08-20T14:00:00Z',
    },
];

export const sampleAdminFilterOptions = {
    statuses: [
        { value: 'pending_payment', label: 'Pending payment' },
        { value: 'received', label: 'Received' },
        { value: 'in_progress', label: 'In progress' },
        { value: 'waiting_for_customer', label: 'Waiting for customer' },
        { value: 'completed', label: 'Completed' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'refunded', label: 'Refunded' },
    ],
    services: [
        { value: 'coins', label: 'Coins' },
        { value: 'sbc', label: 'SBC' },
        { value: 'objectives', label: 'Objectives' },
        { value: 'rivals', label: 'Division Rivals' },
        { value: 'fut_champions', label: 'FUT Champions' },
    ],
    platforms: [
        { value: 'playstation', label: 'PlayStation' },
        { value: 'xbox', label: 'Xbox' },
        { value: 'pc', label: 'PC' },
    ],
    paymentStatuses: [
        { value: 'pending', label: 'Pending' },
        { value: 'authorized', label: 'Authorized' },
        { value: 'paid', label: 'Paid' },
        { value: 'failed', label: 'Failed' },
        { value: 'partially_refunded', label: 'Partially refunded' },
        { value: 'refunded', label: 'Refunded' },
    ],
    perPageOptions: [15, 25, 50, 100],
};

export const sampleAdminPagination = {
    currentPage: 1,
    lastPage: 3,
    perPage: 15 as const,
    total: 35,
    from: 1,
    to: 15,
};

export const sampleAdminOrderDetail = {
    id: '01K5ADM1N00000000000000001',
    orderNumber: 'AUT-1001',
    status: 'received',
    currency: 'SAR',
    placedAt: '2026-08-20T10:00:00Z',
    paidAt: '2026-08-20T10:05:00Z',
    completedAt: null,
    cancelledAt: null,
    customer: {
        id: '01K5CUST00000000000000001',
        name: 'Saud Al-Otaibi',
        email: 'saud@example.test',
        phone: '+966500000001',
    },
    money: {
        subtotal: { amountMinor: '15000', currency: 'SAR' as const },
        discount: { amountMinor: '0', currency: 'SAR' as const },
        wallet: { amountMinor: '0', currency: 'SAR' as const },
        payment: { amountMinor: '15000', currency: 'SAR' as const },
        total: { amountMinor: '15000', currency: 'SAR' as const },
    },
    items: [
        {
            id: '01K5ITEM00000000000000001',
            name: 'Coins Service',
            serviceType: 'coins',
            platform: 'playstation',
            quantity: 1,
            unitPrice: { amountMinor: '15000', currency: 'SAR' as const },
            subtotal: { amountMinor: '15000', currency: 'SAR' as const },
            discount: { amountMinor: '0', currency: 'SAR' as const },
            total: { amountMinor: '15000', currency: 'SAR' as const },
            status: 'received',
            configuration: null,
            hasSecret: false,
            maskedSummary: null,
            statusHistory: [],
        },
    ],
    payments: [
        {
            id: '01K5PAY00000000000000001',
            status: 'paid',
            currency: 'SAR',
            amount: { amountMinor: '15000', currency: 'SAR' as const },
            capturedAmount: { amountMinor: '15000', currency: 'SAR' as const },
            refundedAmount: { amountMinor: '0', currency: 'SAR' as const },
            paidAt: '2026-08-20T10:05:00Z',
            createdAt: '2026-08-20T10:00:00Z',
        },
    ],
    refunds: [],
    discounts: [],
    statusHistory: [
        {
            id: '01K5HIST00000000000000001',
            status: 'received',
            source: 'system',
            previousStatus: 'pending_payment',
            newStatus: 'received',
            createdAt: '2026-08-20T10:05:00Z',
            actor: null,
        },
    ],
    auditContext: [
        {
            id: '01K5AUD00000000000000001',
            action: 'orders.viewed',
            actor: { name: 'Operations Owner', role: 'admin' },
            createdAt: '2026-08-20T10:10:00Z',
        },
    ],
};
